package handlers

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"sysmetrics-mcp/internal/config"
	"sysmetrics-mcp/internal/monitor"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

// RegisterMonitoringTools registers the streaming and alerting tools.
func (h *HandlerManager) RegisterMonitoringTools(s *server.MCPServer) {
	s.AddTool(mcp.NewTool("start_monitoring",
		mcp.WithDescription("Start background sampling of system metrics. Returns a snapshot and enables history and alerts."),
		mcp.WithNumber("interval", mcp.Description("Sampling interval in seconds (overrides config default)"))),
		h.HandleStartMonitoring)

	s.AddTool(mcp.NewTool("stop_monitoring",
		mcp.WithDescription("Stop background sampling of system metrics.")),
		h.HandleStopMonitoring)

	s.AddTool(mcp.NewTool("get_monitoring_status",
		mcp.WithDescription("Get the current monitoring status, latest snapshot, and buffered alerts.")),
		h.HandleGetMonitoringStatus)

	s.AddTool(mcp.NewTool("get_metrics_history",
		mcp.WithDescription("Get recent metric snapshots captured by the monitor."),
		mcp.WithNumber("seconds", mcp.Description("Return snapshots captured within the last N seconds"))),
		h.HandleGetMetricsHistory)

	s.AddTool(mcp.NewTool("get_alerts",
		mcp.WithDescription("Get threshold alerts generated by the monitor since the last read."),
		mcp.WithString("severity", mcp.Description("Filter by severity: warning or critical"),
			mcp.Enum("warning", "critical"))),
		h.HandleGetAlerts)

	s.AddTool(mcp.NewTool("get_network_throughput",
		mcp.WithDescription("Get per-interface network throughput rates (bytes/sec) since the last sample.")),
		h.HandleGetNetworkThroughput)

	s.AddTool(mcp.NewTool("get_disk_throughput",
		mcp.WithDescription("Get per-device disk I/O throughput rates (bytes/sec and IOPS) since the last sample.")),
		h.HandleGetDiskThroughput)
}

// HandleStartMonitoring starts background sampling.
func (h *HandlerManager) HandleStartMonitoring(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	interval := time.Duration(h.cfg.MonitorInterval) * time.Second

	if args, ok := request.Params.Arguments.(map[string]interface{}); ok {
		if v, ok := args["interval"].(float64); ok && v > 0 {
			secs := int(v)
			if secs > config.MaxMonitorInterval {
				secs = config.MaxMonitorInterval
			}
			interval = time.Duration(secs) * time.Second
		}
	}

	started := h.monitor.Start(interval)
	snap, _ := h.monitor.Last()

	result := map[string]interface{}{
		"started":          started,
		"already_running":  !started && h.monitor.IsRunning(),
		"interval_seconds": int(interval / time.Second),
		"latest_snapshot":  snap,
	}

	return h.marshalResult(result)
}

// HandleStopMonitoring stops background sampling.
func (h *HandlerManager) HandleStopMonitoring(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	wasRunning := h.monitor.IsRunning()
	h.monitor.Stop()
	return h.marshalResult(map[string]interface{}{
		"was_running": wasRunning,
		"is_running":  h.monitor.IsRunning(),
	})
}

// HandleGetMonitoringStatus reports monitor state plus latest snapshot/alerts.
func (h *HandlerManager) HandleGetMonitoringStatus(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	snap, hasSnap := h.monitor.Last()
	result := map[string]interface{}{
		"running":          h.monitor.IsRunning(),
		"interval_seconds": int(h.monitor.Interval() / time.Second),
		"status":           h.monitor.Status(),
		"has_snapshot":     hasSnap,
		"latest_snapshot":  snap,
	}
	return h.marshalResult(result)
}

// HandleGetMetricsHistory returns recent snapshots.
func (h *HandlerManager) HandleGetMetricsHistory(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	var seconds float64
	if args, ok := request.Params.Arguments.(map[string]interface{}); ok {
		if v, ok := args["seconds"].(float64); ok && v > 0 {
			seconds = v
		}
	}

	var history []monitor.Snapshot
	if seconds > 0 {
		since := time.Now().Add(-time.Duration(seconds * float64(time.Second)))
		history = h.monitor.History()
		filtered := history[:0]
		for _, s := range history {
			if !s.Timestamp.Before(since) {
				filtered = append(filtered, s)
			}
		}
		history = filtered
	} else {
		history = h.monitor.History()
	}

	result := map[string]interface{}{
		"count":   len(history),
		"running": h.monitor.IsRunning(),
		"samples": history,
	}
	return h.marshalResult(result)
}

// HandleGetAlerts returns buffered alerts, optionally filtered by severity.
func (h *HandlerManager) HandleGetAlerts(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	var severityFilter string
	if args, ok := request.Params.Arguments.(map[string]interface{}); ok {
		if s, ok := args["severity"].(string); ok && s != "" {
			severityFilter = strings.ToLower(s)
		}
	}

	alerts := h.monitor.DrainAlerts()
	if severityFilter != "" {
		filtered := alerts[:0]
		for _, a := range alerts {
			if a.Severity == severityFilter {
				filtered = append(filtered, a)
			}
		}
		alerts = filtered
	}

	result := map[string]interface{}{
		"count":  len(alerts),
		"alerts": alerts,
	}
	return h.marshalResult(result)
}

// HandleGetNetworkThroughput returns current per-interface rates.
func (h *HandlerManager) HandleGetNetworkThroughput(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	snap, err := h.monitor.SampleNow(ctx)
	if err != nil {
		return mcp.NewToolResultError(fmt.Sprintf("Failed to sample network throughput: %v", err)), nil
	}

	result := map[string]interface{}{
		"timestamp":  snap.Timestamp,
		"interfaces": snap.Net,
	}
	return h.marshalResult(result)
}

// HandleGetDiskThroughput returns current per-device rates.
func (h *HandlerManager) HandleGetDiskThroughput(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	snap, err := h.monitor.SampleNow(ctx)
	if err != nil {
		return mcp.NewToolResultError(fmt.Sprintf("Failed to sample disk throughput: %v", err)), nil
	}

	result := map[string]interface{}{
		"timestamp": snap.Timestamp,
		"devices":   snap.DiskIO,
	}
	return h.marshalResult(result)
}

// marshalResult encodes a payload as an MCP tool result.
func (h *HandlerManager) marshalResult(payload interface{}) (*mcp.CallToolResult, error) {
	jsonBytes, err := json.Marshal(payload)
	if err != nil {
		return mcp.NewToolResultError(fmt.Sprintf("Failed to marshal result: %v", err)), nil
	}
	return mcp.NewToolResultText(string(jsonBytes)), nil
}
